# Generated by Django 5.2.1 on 2025-07-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload candidate photo (recommended size: 400x400px)', null=True, upload_to='candidates/'),
        ),
    ]
