# Generated by Django 5.2.1 on 2025-07-06 23:12

import cloudinary_storage.storage
import elections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload candidate photo (recommended size: 400x400px)', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=elections.models.candidate_photo_path),
        ),
    ]
