# Generated by Django 5.2.1 on 2026-06-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_candidate_photo_otpverification'),
        ('elections', '0003_alter_candidate_photo'),
    ]

    operations = [
    ]
